version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_aws}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack  Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - waitForTcpPorts=false
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EAGER_SERVICE_LOADING=1
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=LOCAL
      - AWS_SECRET_ACCESS_KEY=LOCAL
      - GATEWAY_LISTEN=0.0.0.0:4566
      - USE_SSL=0
      # Define services here
      - SERVICES=s3,dynamodb,lambda,sqs,sns
      # S3 config
      - S3_DIRS=/tmp/s3-buckets
      # DynamoDB config
      - DYNAMODB_SHARE_DB=1
      - DYNAMODB_DELAY_TRANSIENT_STATUSES=1
      # Lambda config
      - LAMBDA_RUNTIME_EXECUTOR=docker
      # SQS
      - SQS_DELAY_RECENTLY_DELETED=1
      - SQS_DELAY_PURGE_RETRY=1
      # EMAIL
      - SMTP_HOST=localhost:5000
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: awslocal dynamodb list-tables
      interval: 1m30s
      timeout: 10s
      retries: 10
