spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: microservice-1
          uri: lb://MICROSERVICE-1/
          predicates:
            - Path=/microservice-1/**
        - id: microservice-2
          uri: lb://MICROSERVICE-2/
          predicates:
            - Path=/microservice-2/**
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"